#!/home/wyb/.miniconda3/envs/worldscanner/bin/python
import cv2
import numpy as np
from numpy.linalg import norm
import os

def brightness(img):
    if len(img.shape) == 3:
        # Colored RGB or BGR (*Do Not* use HSV images with this function)
        # create brightness with euclidean norm
        return np.average(norm(img, axis=2)) / np.sqrt(3)
    else:
        # Grayscale
        return np.average(img)

os.system("v4l2-ctl -c white_balance_automatic=0")
cam = cv2.VideoCapture(0)
os.system("v4l2-ctl -c white_balance_automatic=1")
ret, frame = cam.read()
if not ret:
    exit()

before = brightness(frame)

for row in range(frame.shape[0]):
    for col in range(frame.shape[1]):
        frame[row][col][2] = 0

after = brightness(frame)

ratio = after / before
temp = int(4000 + (ratio - 0.7) / 0.3 * 6000)
print(before, after, after/before)

cmd = f"gsettings set org.gnome.settings-daemon.plugins.color night-light-temperature {temp}"
os.system(cmd)

print(cmd)
cam.release()

